'use strict';

const { listProviders } = require('./providers-catalog');

const DEFAULT_BIND_WHITELIST = [
  'AF', 'AM', 'CW', 'AO', 'AX', 'BD', 'BF', 'BG', 'BI', 'BL', 'BO', 'CA', 'CC', 'CF', 'CM', 'CX',
  'DZ', 'EC', 'EG', 'EH', 'ET', 'FK', 'FR', 'GH', 'GN', 'GW', 'HN', 'HT', 'ID', 'IO', 'JM', 'JO',
  'JP', 'KG', 'KH', 'KM', 'KR', 'LB', 'LK', 'LY', 'ME', 'MF', 'MG', 'ML', 'MN', 'MP', 'MU', 'MY',
  'MZ', 'NG', 'NU', 'PE', 'PK', 'PN', 'PS', 'SA', 'SD', 'SH', 'SI', 'SJ', 'SL', 'SM', 'SN', 'TG',
  'TH', 'TJ', 'TK', 'TL', 'TM', 'TW', 'UG', 'UM', 'US', 'UZ', 'VA', 'VN', 'VU', 'RS', 'ZM', 'ZW',
];

const DEFAULT_RECOMMENDED_WHITELIST = [
  'ID', 'PH', 'CO', 'UA', 'NL', 'BR', 'PL', 'GB', 'CA', 'MX', 'IL', 'FR', 'SE', 'TH', 'HK',
];

/** Provider service codes for OnlineSim, SMSPVA, CodesVerify, SMSCode.net, SMS-Rooms. */
const EXTENDED_PROVIDER_CODES = {
  openai_chatgpt: {
    onlinesim: 'openai',
    smspva: 'opt132',
    codesverify: 'openai',
    smscode: 'ChatGPT',
    'sms-rooms': 'dr',
    'sms-bus': 'openai',
    'vibe-sms': 'dr',
    cyberyozh: 'dr',
    'vak-sms': 'dr',
    'give-sms': 'dr',
    '365sms': 'dr',
    'juicy-sms': 'dr',
    'tiger-sms': 'dr',
    pvapins: 'dr',
    simsms: 'opt132',
    getsms: 'OpenAI',
    'fangyuan-sms': '127',
  },
  telegram: {
    onlinesim: 'telegram',
    smspva: 'opt29',
    codesverify: 'telegram',
    smscode: 'Telegram',
    'sms-rooms': 'tg',
    'sms-bus': 'tg',
    'vibe-sms': 'tg',
    cyberyozh: 'tg',
    'vak-sms': 'tg',
    'give-sms': 'tg',
    '365sms': 'tg',
    'juicy-sms': 'tg',
    'tiger-sms': 'tg',
    smstg: 'tg',
    pvapins: 'tg',
    simsms: 'opt29',
    getsms: 'Telegram',
    'fangyuan-sms': '5',
  },
  whatsapp: {
    onlinesim: 'whatsapp',
    smspva: 'opt20',
    codesverify: 'whatsapp',
    smscode: 'Whatsapp',
    'sms-rooms': 'wa',
    'sms-bus': 'wa',
    'vibe-sms': 'wa',
    cyberyozh: 'wa',
    'vak-sms': 'wa',
    'give-sms': 'wa',
    '365sms': 'wa',
    'juicy-sms': 'wa',
    'tiger-sms': 'wa',
    pvapins: 'wa',
    simsms: 'opt20',
    getsms: 'WhatsApp',
    'fangyuan-sms': '2',
  },
  google: {
    onlinesim: 'google',
    smspva: 'opt1',
    codesverify: 'google',
    smscode: 'Google',
    'sms-rooms': 'go',
    'sms-bus': 'google',
    'vibe-sms': 'go',
    cyberyozh: 'go',
    'vak-sms': 'go',
    'give-sms': 'go',
    '365sms': 'go',
    'juicy-sms': 'go',
    'tiger-sms': 'go',
    pvapins: 'go',
    simsms: 'opt1',
    getsms: 'Google',
    'fangyuan-sms': '6',
  },
  discord: {
    onlinesim: 'discord',
    smspva: 'opt45',
    codesverify: 'discord',
    smscode: 'Discord',
    'sms-rooms': 'ds',
    'sms-bus': 'discord',
    'vibe-sms': 'ds',
    cyberyozh: 'ds',
    'vak-sms': 'ds',
    'give-sms': 'ds',
    '365sms': 'ds',
    'juicy-sms': 'ds',
    'tiger-sms': 'ds',
    pvapins: 'ds',
    simsms: 'opt45',
    getsms: 'Discord',
    'fangyuan-sms': '67',
  },
  microsoft: {
    onlinesim: 'microsoft',
    smspva: 'opt15',
    codesverify: 'microsoft',
    smscode: 'Microsoft',
    'sms-rooms': 'mm',
    'sms-bus': 'microsoft',
    'vibe-sms': 'mm',
    cyberyozh: 'mm',
    'vak-sms': 'mm',
    'give-sms': 'mm',
    '365sms': 'mm',
    'juicy-sms': 'mm',
    'tiger-sms': 'mm',
    pvapins: 'mm',
    simsms: 'opt15',
    getsms: 'Microsoft',
    'fangyuan-sms': '23',
  },
  twitter: {
    onlinesim: 'twitter',
    smspva: 'opt41',
    codesverify: 'twitter',
    smscode: 'Twitter',
    'sms-rooms': 'tw',
    'sms-bus': 'tw',
    'vibe-sms': 'tw',
    cyberyozh: 'tw',
    'vak-sms': 'tw',
    'give-sms': 'tw',
    '365sms': 'tw',
    'juicy-sms': 'tw',
    'tiger-sms': 'tw',
    pvapins: 'tw',
    simsms: 'opt41',
    getsms: 'Twitter',
    'fangyuan-sms': '22',
  },
  instagram: {
    onlinesim: 'instagram',
    smspva: 'opt16',
    codesverify: 'instagram',
    smscode: 'Instagram',
    'sms-rooms': 'ig',
    'sms-bus': 'ig',
    'vibe-sms': 'ig',
    cyberyozh: 'ig',
    'vak-sms': 'ig',
    'give-sms': 'ig',
    '365sms': 'ig',
    'juicy-sms': 'ig',
    'tiger-sms': 'ig',
    pvapins: 'ig',
    simsms: 'opt16',
    getsms: 'Instagram',
    'fangyuan-sms': '24',
  },
  facebook: {
    onlinesim: '3223',
    smspva: 'opt2',
    codesverify: 'facebook',
    smscode: 'Facebook',
    'sms-rooms': 'fb',
    'sms-bus': 'fb',
    'vibe-sms': 'fb',
    cyberyozh: 'fb',
    'vak-sms': 'fb',
    'give-sms': 'fb',
    '365sms': 'fb',
    'juicy-sms': 'fb',
    'tiger-sms': 'fb',
    pvapins: 'fb',
    simsms: 'opt2',
    getsms: 'Facebook',
    'fangyuan-sms': '7',
  },
  tiktok: {
    onlinesim: 'tiktok',
    smspva: 'opt104',
    codesverify: 'tiktok',
    smscode: 'TikTok',
    'sms-rooms': 'lf',
    'sms-bus': 'tk',
    'vibe-sms': 'lf',
    cyberyozh: 'lf',
    'vak-sms': 'lf',
    'give-sms': 'lf',
    '365sms': 'lf',
    'juicy-sms': 'lf',
    'tiger-sms': 'lf',
    pvapins: 'lf',
    simsms: 'opt104',
    getsms: 'TikTok',
    'fangyuan-sms': '126',
  },
  amazon: {
    onlinesim: 'amazon',
    smspva: 'opt44',
    codesverify: 'amazon',
    smscode: 'Amazon',
    'sms-rooms': 'am',
    'sms-bus': 'amz',
    'vibe-sms': 'am',
    cyberyozh: 'am',
    'vak-sms': 'am',
    'give-sms': 'am',
    '365sms': 'am',
    'juicy-sms': 'am',
    'tiger-sms': 'am',
    pvapins: 'am',
    simsms: 'opt44',
    getsms: 'Amazon',
    'fangyuan-sms': '31',
  },
  apple: {
    onlinesim: 'apple',
    smspva: 'opt131',
    codesverify: 'apple',
    smscode: 'Apple',
    'sms-rooms': 'wx',
    'sms-bus': 'apple',
    'vibe-sms': 'wx',
    cyberyozh: 'wx',
    'vak-sms': 'wx',
    'give-sms': 'wx',
    '365sms': 'wx',
    'juicy-sms': 'wx',
    'tiger-sms': 'wx',
    pvapins: 'wx',
    simsms: 'opt131',
    getsms: 'Apple',
    'fangyuan-sms': '42',
  },
};

/**
 * Multi-service catalog.
 * `codes` maps providerKey → upstream service/product code.
 * Activate-compatible providers (Hero/Grizzly/SMSBower/...) share SMS-Activate style codes.
 */
const SERVICES = [
  {
    serviceKey: 'openai_chatgpt',
    displayName: 'OPENAI (ChatGPT)',
    category: 'ai',
    modes: ['register', 'bind', 'recommended', 'whatsapp'],
    bindWhitelistIso2: DEFAULT_BIND_WHITELIST,
    recommendedWhitelistIso2: DEFAULT_RECOMMENDED_WHITELIST,
    codes: {
      'hero-sms': process.env.HERO_SMS_SERVICE_CODE || 'dr',
      smsbower: process.env.SMSBOWER_SERVICE_CODE || 'dr',
      '5sim': process.env.FIVESIM_SERVICE_CODE || 'openai',
      nexsms: process.env.NEXSMS_SERVICE_CODE || 'dr',
      grizzlysms: process.env.GRIZZLYSMS_SERVICE_CODE || 'dr',
      'tiger-sms': process.env.TIGER_SMS_SERVICE_CODE || 'dr',
      'sms-verification-number': process.env.SMS_VERIFICATION_SERVICE_CODE || 'dr',
      smspool: process.env.SMSPOOL_SERVICE_CODE || '671',
    },
    nativeNames: {
      smspool: process.env.SMSPOOL_NATIVE_SERVICE_NAME || 'OpenAI / ChatGPT',
    },
  },
  {
    serviceKey: 'telegram',
    displayName: 'Telegram',
    category: 'messaging',
    modes: ['all'],
    codes: {
      'hero-sms': 'tg',
      smsbower: 'tg',
      '5sim': 'telegram',
      nexsms: 'tg',
      grizzlysms: 'tg',
      'tiger-sms': 'tg',
      'sms-verification-number': 'tg',
      smspool: '903',
    },
    nativeNames: { smspool: 'Telegram' },
  },
  {
    serviceKey: 'whatsapp',
    displayName: 'WhatsApp',
    category: 'messaging',
    modes: ['all'],
    codes: {
      'hero-sms': 'wa',
      smsbower: 'wa',
      '5sim': 'whatsapp',
      nexsms: 'wa',
      grizzlysms: 'wa',
      'tiger-sms': 'wa',
      'sms-verification-number': 'wa',
      smspool: '1012',
    },
    nativeNames: { smspool: 'WhatsApp' },
  },
  {
    serviceKey: 'google',
    displayName: 'Google',
    category: 'account',
    modes: ['all'],
    codes: {
      'hero-sms': 'go',
      smsbower: 'go',
      '5sim': 'google',
      nexsms: 'go',
      grizzlysms: 'go',
      'tiger-sms': 'go',
      'sms-verification-number': 'go',
      smspool: '142',
    },
    nativeNames: { smspool: 'Google' },
  },
  {
    serviceKey: 'discord',
    displayName: 'Discord',
    category: 'messaging',
    modes: ['all'],
    codes: {
      'hero-sms': 'ds',
      smsbower: 'ds',
      '5sim': 'discord',
      nexsms: 'ds',
      grizzlysms: 'ds',
      'tiger-sms': 'ds',
      'sms-verification-number': 'ds',
      smspool: '461',
    },
    nativeNames: { smspool: 'Discord' },
  },
  {
    serviceKey: 'microsoft',
    displayName: 'Microsoft',
    category: 'account',
    modes: ['all'],
    codes: {
      'hero-sms': 'mm',
      smsbower: 'mm',
      '5sim': 'microsoft',
      nexsms: 'mm',
      grizzlysms: 'mm',
      'tiger-sms': 'mm',
      'sms-verification-number': 'mm',
      smspool: '465',
    },
    nativeNames: { smspool: 'Microsoft' },
  },
  {
    serviceKey: 'twitter',
    displayName: 'Twitter / X',
    category: 'social',
    modes: ['all'],
    codes: {
      'hero-sms': 'tw',
      smsbower: 'tw',
      '5sim': 'twitter',
      nexsms: 'tw',
      grizzlysms: 'tw',
      'tiger-sms': 'tw',
      'sms-verification-number': 'tw',
      smspool: '6',
    },
    nativeNames: { smspool: 'Twitter' },
  },
  {
    serviceKey: 'instagram',
    displayName: 'Instagram',
    category: 'social',
    modes: ['all'],
    codes: {
      'hero-sms': 'ig',
      smsbower: 'ig',
      '5sim': 'instagram',
      nexsms: 'ig',
      grizzlysms: 'ig',
      'tiger-sms': 'ig',
      'sms-verification-number': 'ig',
      smspool: '17',
    },
    nativeNames: { smspool: 'Instagram' },
  },
  {
    serviceKey: 'facebook',
    displayName: 'Facebook',
    category: 'social',
    modes: ['all'],
    codes: {
      'hero-sms': 'fb',
      smsbower: 'fb',
      '5sim': 'facebook',
      nexsms: 'fb',
      grizzlysms: 'fb',
      'tiger-sms': 'fb',
      'sms-verification-number': 'fb',
      smspool: '7',
    },
    nativeNames: { smspool: 'Facebook' },
  },
  {
    serviceKey: 'tiktok',
    displayName: 'TikTok',
    category: 'social',
    modes: ['all'],
    codes: {
      'hero-sms': 'lf',
      smsbower: 'lf',
      '5sim': 'tiktok',
      nexsms: 'lf',
      grizzlysms: 'lf',
      'tiger-sms': 'lf',
      'sms-verification-number': 'lf',
      smspool: '1070',
    },
    nativeNames: { smspool: 'TikTok' },
  },
  {
    serviceKey: 'amazon',
    displayName: 'Amazon',
    category: 'commerce',
    modes: ['all'],
    codes: {
      'hero-sms': 'am',
      smsbower: 'am',
      '5sim': 'amazon',
      nexsms: 'am',
      grizzlysms: 'am',
      'tiger-sms': 'am',
      'sms-verification-number': 'am',
      smspool: '44',
    },
    nativeNames: { smspool: 'Amazon' },
  },
  {
    serviceKey: 'apple',
    displayName: 'Apple',
    category: 'account',
    modes: ['all'],
    codes: {
      'hero-sms': 'wx',
      smsbower: 'wx',
      '5sim': 'apple',
      nexsms: 'wx',
      grizzlysms: 'wx',
      'tiger-sms': 'wx',
      'sms-verification-number': 'wx',
      smspool: '1438',
    },
    nativeNames: { smspool: 'Apple' },
  },
];

for (const service of SERVICES) {
  const extraCodes = EXTENDED_PROVIDER_CODES[service.serviceKey];
  if (extraCodes) {
    Object.assign(service.codes, extraCodes);
    service.nativeNames = {
      ...(service.nativeNames || {}),
      smscode: extraCodes.smscode,
      getsms: extraCodes.getsms,
    };
  }
}

function listServices() {
  return SERVICES.map((service) => ({
    serviceKey: service.serviceKey,
    displayName: service.displayName,
    category: service.category,
    modes: service.modes || ['all'],
  }));
}

function getServiceDefinition(serviceKey) {
  return SERVICES.find((service) => service.serviceKey === serviceKey) || null;
}

function buildServiceConfig(serviceKey = 'openai_chatgpt') {
  const service = getServiceDefinition(serviceKey) || getServiceDefinition('openai_chatgpt');
  const providers = listProviders();

  return {
    serviceKey: service.serviceKey,
    displayName: service.displayName,
    category: service.category,
    modes: service.modes || ['all'],
    bindWhitelistIso2: service.bindWhitelistIso2 || [],
    recommendedWhitelistIso2: service.recommendedWhitelistIso2 || [],
    providerMappings: providers.map((provider) => ({
      ...provider,
      serviceCode: service.codes?.[provider.providerKey] || '',
      nativeServiceName: service.nativeNames?.[provider.providerKey] || '',
    })),
  };
}

/** Backward-compatible default export shape used by older call sites. */
const defaultConfig = buildServiceConfig('openai_chatgpt');

module.exports = {
  ...defaultConfig,
  SERVICES,
  buildServiceConfig,
  getServiceDefinition,
  listServices,
};
